spring:
  application:
    name: aimoviesearcher
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-3.1-flash-lite
tmdb:
  api:
    base-url: https://api.themoviedb.org/3
    token: ${TMDB_BEARER_TOKEN}